# Generated by Django 6.0.1 on 2026-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_status_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locks final mark and prevents further grade changes'),
        ),
    ]
