# Generated by Django 6.0.1 on 2026-02-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollment_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
    ]
