# Generated by Django 6.0.5 on 2026-05-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_remove_enrollment_is_locked_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locks final mark and prevents further grade changes'),
        ),
    ]
