# Generated by Django 6.0.1 on 2026-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
