# Generated by Django 6.0.1 on 2026-01-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_lecturer_alter_enrollment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aggregation_method', models.CharField(choices=[('AVERAGE', 'Average'), ('BEST', 'Best Of'), ('SUM', 'Sum')], default='AVERAGE', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_locked', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.assessmentcomponent')),
            ],
        ),
    ]
