# Generated by Django 6.0.5 on 2026-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlog',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Duration in hours e.g. 1.5', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classlog',
            name='start_time',
            field=models.TimeField(default=1.0),
            preserve_default=False,
        ),
    ]
