# Generated by Django 6.0.1 on 2026-01-23 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_unique_together_and_more'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'assessment_item')},
        ),
    ]
