# Generated by Django 6.0.1 on 2026-01-24 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_grade_enrollment_grade_recorded_by_delete_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentitem',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='assessmentcomponent',
            name='aggregation_method',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='assessmentcomponent',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Percentage contribution to final mark', max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='recorded_by',
        ),
    ]
