# Generated by Django 6.0.1 on 2026-01-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_title_assessmentitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
